# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:11
    working_directory: ~/repo

aliases:
  restore_cache: &restore_cache
    restore_cache:
      name: Restore node_modules cache
      keys:
        - yarn-cypress-cache-{{ checksum "yarn.lock" }}
        
  install_node_modules: &install_node_modules
    run:
      name: Install node modules
      command: yarn --frozen-lockfile
      
  persist_cache: &persist_cache
    save_cache:
      name: Save node modules cache
      key: yarn-cypress-cache-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache
        
  attach_to_build: &attach_to_build
    attach_workspace:
      at: public

jobs:

  build:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *persist_cache
      - run: yarn gatsby-build
      - persist_to_workspace:
          root: public
          paths:
            - "*"

  test:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *persist_cache
      - run: yarn test

  test-e2e:
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *persist_cache
      - <<: *attach_to_build
      - run:
          command: yarn run e2e-test
      - store_test_results:
          path: results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

  deploy:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *persist_cache
      - <<: *attach_to_build
      - run: yarn deploy

workflows:
  version: 2

  test-and-deploy:
    jobs:
      - build
      - test
      - test-e2e:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
            - test-e2e
          filters:
            branches:
              only: master
